import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

/**
 * publisher.js
 *
 * Handles the local file write and git pipeline (add → commit → push)
 * to the user's public daily-learnings journal repository.
 */

/**
 * Writes the AI-generated summary to the journal repo as a dated markdown file,
 * then stages, commits, and pushes the change to GitHub.
 *
 * @param {string} journalRepoPath - Absolute path to the local journal repo
 * @param {string} markdownSummary - AI-generated bullet points
 * @returns {{ filePath: string, isNewFile: boolean, commitHash: string }}
 */
export function publishJournal(journalRepoPath, markdownSummary) {
  // ── Resolve the target markdown file ────────────────────────────────────
  const today = getTodayDateString();
  const fileName = `${today}.md`;
  const filePath = path.join(journalRepoPath, fileName);

  // ── Build the journal entry block ────────────────────────────────────────
  const timestamp = new Date().toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  });

  const isNewFile = !fs.existsSync(filePath);

  let fileContent;

  if (isNewFile) {
    // First sync of the day — create the file with a full header
    const dateHeader = formatDateHeader(today);
    fileContent = buildNewDayEntry(dateHeader, markdownSummary, timestamp);
  } else {
    // Subsequent sync — read existing content and append a new section
    const existing = fs.readFileSync(filePath, 'utf-8');
    fileContent = appendToEntry(existing, markdownSummary, timestamp);
  }

  // ── Write to disk ────────────────────────────────────────────────────────
  fs.writeFileSync(filePath, fileContent, 'utf-8');

  // ── Git pipeline: add → commit → push ────────────────────────────────────
  const commitMessage = `docs: daily journal update — ${today}`;
  const commitHash = runGitPipeline(journalRepoPath, commitMessage);

  return { filePath, isNewFile, commitHash };
}

/**
 * Runs the full git pipeline inside the journal repo directory.
 * Throws a descriptive error if any step fails.
 *
 * @param {string} repoPath
 * @param {string} commitMessage
 * @returns {string} Short commit hash
 */
function runGitPipeline(repoPath, commitMessage) {
  const execOptions = {
    cwd: repoPath,
    encoding: 'utf-8',
    stdio: ['pipe', 'pipe', 'pipe'],
  };

  try {
    // Stage all changes
    execSync('git add .', execOptions);
  } catch (err) {
    throw new PublishError(`git add failed: ${err.stderr?.trim() || err.message}`, 'GIT_ADD');
  }

  try {
    // Commit
    execSync(`git commit -m "${commitMessage}"`, execOptions);
  } catch (err) {
    const stderr = err.stderr?.trim() || '';
    if (stderr.includes('nothing to commit')) {
      // No actual changes — this is fine, not an error
      return 'nothing-to-commit';
    }
    throw new PublishError(`git commit failed: ${stderr || err.message}`, 'GIT_COMMIT');
  }

  try {
    // Push to remote
    execSync('git push origin main', execOptions);
  } catch (err) {
    const stderr = err.stderr?.trim() || '';
    // Try 'master' as fallback if 'main' doesn't exist
    if (stderr.includes("error: src refspec main does not match any")) {
      try {
        execSync('git push origin master', execOptions);
      } catch (err2) {
        throw new PublishError(`git push failed: ${err2.stderr?.trim() || err2.message}`, 'GIT_PUSH');
      }
    } else {
      throw new PublishError(`git push failed: ${stderr || err.message}`, 'GIT_PUSH');
    }
  }

  // Return the short commit hash for display
  try {
    return execSync('git rev-parse --short HEAD', execOptions).trim();
  } catch {
    return 'unknown';
  }
}

// ─── Entry Formatting Helpers ─────────────────────────────────────────────────

function buildNewDayEntry(dateHeader, summary, timestamp) {
  return `# ${dateHeader}

${summary}

---

*Last updated at ${timestamp} · Generated by [devjournal](https://github.com/notmanjit/devjournal)*
`;
}

function appendToEntry(existing, summary, timestamp) {
  // Replace the last-updated line at the bottom with new content + updated timestamp
  const separator = '\n\n---\n\n';
  const footer = `\n\n---\n\n*Last updated at ${timestamp} · Generated by [devjournal](https://github.com/notmanjit/devjournal)*\n`;

  // Strip old footer
  const strippedExisting = existing
    .replace(/\n\n---\n\n\*Last updated at.*\n$/s, '')
    .trimEnd();

  return `${strippedExisting}${separator}## Update — ${timestamp}\n\n${summary}${footer}`;
}

function getTodayDateString() {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function formatDateHeader(dateString) {
  const date = new Date(dateString + 'T12:00:00'); // noon to avoid timezone edge cases
  return date.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

// ─── Custom Error Class ───────────────────────────────────────────────────────
export class PublishError extends Error {
  constructor(message, code) {
    super(message);
    this.name = 'PublishError';
    this.code = code;
  }
}
